
services:
  restaurant-app:
    image: restaurant-predictor:0.4
    container_name: restaurant_app
    ports:
      - "8501:8501"
    environment:
      STREAMLIT_SERVER_PORT: 8501
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0
    restart: unless-stopped